- hosts: local
  vars_files:
    - vars.yml

  tasks:

    - name: Check logs folder permissions
      file:
        path: "{{ working_folder }}/logs"
        state: directory
        group: "{{ so_user }}"
        owner: "{{ so_user }}"
        recurse: yes
      sudo: yes

    - name: Check static folder permissions
      file:
        path: "{{ working_folder }}/static"
        state: directory
        group: "{{ so_user }}"
        owner: "{{ so_user }}"
        recurse: yes
      sudo: yes

    - name: Check docker folder permissions
      file:
        path: "{{ working_folder }}/docker"
        state: directory
        group: "{{ so_user }}"
        owner: "{{ so_user }}"
        recurse: yes
      sudo: yes

    - name: Check postgres folder permissions
      file:
        path: "{{ working_folder }}/psql_data"
        state: directory
        group: "{{ so_user }}"
        owner: "{{ so_user }}"
        recurse: yes
      sudo: yes

    - name: Start a new postgres container
      docker:
        image: "{{ psql_image }}"
        name: "{{ runbot_db }}"
        env: "POSTGRES_USER=runbot,POSTGRES_PASSWORD={{ psql_password }}"
        volumes:
          - "{{ working_folder }}/psql_data:/var/lib/postgresql/data"
        pull: "missing"
        publish_all_ports: yes

    - name: Build runbot image
      docker_image:
        name: "{{ runbot_image_name }}"
        nocache: no
        tag: "{{ runbot_image_tag }}"
        path: "{{ dockerfile_path }}"
        state: build

    - name: Start a new runbot container
      docker:
        image: "{{ runbot_image_name }}:{{ runbot_image_tag }}"
        name: "{{ runbot_container_name }}"
        command: "/entrypoint.sh"
        hostname: "{{ runbot_hostname }}"
        publish_all_ports: yes
        privileged: yes
        volumes:
          - "{{ working_folder }}/static:/home/runbot/instance/extra_addons/odoo-extra/runbot/static"
          - "{{ working_folder }}/logs:/var/log/supervisor"
          - "{{ working_folder }}/docker:/var/lib/docker"
        links:
          - "{{ runbot_db }}:dbrunbot"

